apiVersion: v2
name: kube-oom-policy
description: Set cgroup v2 group OOM behavior for selected Kubernetes containers.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/ignacyr/kube-oom-policy
sources:
  - https://github.com/ignacyr/kube-oom-policy
keywords:
  - kubernetes
  - cgroup
  - oom
